#!/usr/bin/env bash

connect_unified() {
	errmsg=$(nmcli connection up id $1 2>&1)
	if [[ $? != 0 ]]; then
		echo "$errmsg"
		if [[ $errmsg == "Error: Connection activation failed: Connection '$1' is already active" ]]; then
			sleep 1200
		else
			sleep 20
		fi;
	else
		sleep 1200
	fi
}

vpn=$1
shift
test -z $vpn && echo 'No vpn.' && exit 1

while true ; do
	connect_unified $vpn; test $? -gt 128 && break;
done
